// <auto-generated />
using Apollo_Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Apollo_Data.Migrations
{
    [DbContext(typeof(DiscordBotContext))]
    [Migration("20180125142938_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Apollo_Data.Entities.QuoteEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("DateAdded");

                    b.Property<DateTimeOffset>("DateUpdated");

                    b.Property<string>("Name");

                    b.Property<string>("Quote");

                    b.Property<ulong?>("ServerEntityId");

                    b.HasKey("Id");

                    b.HasIndex("ServerEntityId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Apollo_Data.Entities.ServerEntity", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong?>("BotChannelId");

                    b.Property<DateTimeOffset>("DateAdded");

                    b.Property<DateTimeOffset>("DateUpdated");

                    b.Property<ulong?>("DeleteLogChannelId");

                    b.Property<string>("GuildName");

                    b.Property<ulong?>("LogChannelId");

                    b.Property<ulong?>("MainChannelId");

                    b.Property<ulong?>("StaffChannelId");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Apollo_Data.Entities.QuoteEntity", b =>
                {
                    b.HasOne("Apollo_Data.Entities.ServerEntity")
                        .WithMany("Quotes")
                        .HasForeignKey("ServerEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
